export const users = [
  {
    id: 1,
    name: "Rik Perago",
    state: null,
    email: "rperago0@ning.com",
    gender: "Male",
    phone: "342-590-6425",
    image: "https://robohash.org/saepeabea.jpg?size=50x50&set=set1",
  },
  {
    id: 2,
    name: "Maxine Bamford",
    state: "Lisboa",
    email: "mbamford1@cbsnews.com",
    gender: "Female",
    phone: "310-401-6068",
    image: "https://robohash.org/nisirepellendusamet.bmp?size=50x50&set=set1",
  },
  {
    id: 3,
    name: "Tatiania Romanini",
    state: "Ilha do Pico",
    email: "tromanini2@sciencedaily.com",
    gender: "Female",
    phone: "842-831-4846",
    image: "https://robohash.org/minimavitaemagni.jpg?size=50x50&set=set1",
  },
  {
    id: 4,
    name: "Elmer Gilardoni",
    state: null,
    email: "egilardoni3@printfriendly.com",
    gender: "Male",
    phone: "880-536-8695",
    image: "https://robohash.org/molestiaeremet.png?size=50x50&set=set1",
  },
  {
    id: 5,
    name: "Valentin Spolton",
    state: null,
    email: "vspolton4@tinypic.com",
    gender: "Male",
    phone: "706-337-1041",
    image: "https://robohash.org/debitissimiliquenon.png?size=50x50&set=set1",
  },
  {
    id: 6,
    name: "Chery Drinnan",
    state: null,
    email: "cdrinnan5@wix.com",
    gender: "Female",
    phone: "977-807-5008",
    image: "https://robohash.org/velprovidentquas.jpg?size=50x50&set=set1",
  },
  {
    id: 7,
    name: "Valentijn Perview",
    state: null,
    email: "vperview6@odnoklassniki.ru",
    gender: "Male",
    phone: "823-357-3235",
    image: "https://robohash.org/officiiseligendiqui.png?size=50x50&set=set1",
  },
  {
    id: 8,
    name: "Wilhelmine Chill",
    state: "Guadeloupe",
    email: "wchill7@washington.edu",
    gender: "Female",
    phone: "518-873-1983",
    image:
      "https://robohash.org/praesentiumevenietmodi.png?size=50x50&set=set1",
  },
  {
    id: 9,
    name: "Howard Trippett",
    state: null,
    email: "htrippett8@nba.com",
    gender: "Male",
    phone: "639-377-8363",
    image: "https://robohash.org/consequunturporroab.png?size=50x50&set=set1",
  },
  {
    id: 10,
    name: "Nevil Pryell",
    state: "Ohio",
    email: "npryell9@taobao.com",
    gender: "Male",
    phone: "513-980-5914",
    image: "https://robohash.org/quodveniamea.jpg?size=50x50&set=set1",
  },
];
